---
title: 'Lab 1: Question 1'
author: "Your Names Here"
output: pdf_document
---

```{r load packages, echo=TRUE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2) 
# library(tidyverse) # if you want more, but still core, toolkit
```

```{r load and clean data, echo=FALSE, warning=TRUE, message=FALSE}
rawDat <- haven::read_dta('anes_timeseries_2020_stata_20210211/anes_timeseries_2020_stata_20210211.dta')

## Select fields
dat <- rawDat %>% select(V201624, V201625, V201145) %>%
  rename(Positive_COVID = V201624,
         COVID_Symptoms = V201625,
         Governor = V201145)

# 1 = Approve
# 2 = Disapprove
dat %<>% filter(Positive_COVID %in% c(1, 2),
                COVID_Symptoms %in% c(1, 2),
                Governor %in% c(1, 2))

dat %>% mutate(Governor = ifelse(Governor == 2, 0, 1)) %>% 
  group_by(Positive_COVID) %>% 
  summarise(totalCount = n(),
            approve = sum(Governor)) %>%
  mutate(pcnt = approve / totalCount)
```


## Importance and Context
<!-- You can (and should delete each of these comments lines in your final report) --> 
<!-- Explain why the reader should care about your research question. -->

## Description of Data
<!-- Explain how your research question is operationalized, including whether the variables you create are appropriate to study the concepts in question. --> 
<!-- What are some basic features of the data distribution? --> 
<!-- What changes do you make to the data and why? --> 

## Most appropriate test 
<!-- Explain which test is the most appropriate to answer your question and why it is the most appropriate --> 
<!-- List every assumption that your test requires and evaluate it. -->

## Test, results and interpretation
<!-- What are the results of your test? --> 
<!-- What do the results of this test mean? What is the practical significance? --> 
